### ISSUE TITLE
Decide on templating language to use instead of Nunjucks and migrate existing Nunjucks templates

### ISSUE THREAD

**Issue by gracexu94** [kindsys/digital-services-coalition#4]
As highlighted by John, we may want to move away from Nunjucks and onto Liquid or WebC instead as a templating language.

Resources:
[1]( https://www.brycewray.com/posts/2023/03/time-move-on-nunjucks/
), [2] (https://github.com/mozilla/nunjucks), [3] ([https://](https://github.com/Shopify/liquid), [4] (https://github.com/11ty/webc)

**Comment by bjariel** [comment]
We are choosing to use Liquid as the template language.

**Comment by SeaJerry** [comment]
The ADR is located in this issue https://github.com/kindsys/digital-services-coalition/issues/12
